# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWF-File
version:      0.33
version_from: lib/SWF/Element.pm
installdirs:  site
requires:
    Data::TemporaryBag:            0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
